version: "3.4"
services:
  mern-chatapp-backend:
    build: ./server
    container_name: mern-chatapp-backend
    networks:
      - mongodb
      - backend
      - proxy
    ports:
      - "5000:3000"
    depends_on:
      - "redis-chatapp"
    environment:
      - NODE_PORT=$NODE_PORT
      - CORS_ORIGIN=$NODE_PORT
      - NODE_ENV=production
      - MONGODB_URL=$MONGODB_URL
      - REDIS_URL=$REDIS_URL
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mern-chatapp-backend.entrypoints=http"
      - "traefik.http.routers.mern-chatapp-backend.rule=Host(`mern-chatapp.brehak.com`) && Path(`/api`)"
      - "traefik.http.middlewares.mern-chatapp-backend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mern-chatapp-backend.middlewares=mern-chatapp-backend-https-redirect"
      - "traefik.http.routers.mern-chatapp-backend-secure.entrypoints=https"
      - "traefik.http.routers.mern-chatapp-backend-secure.rule=Host(`mern-chatapp.brehak.com`) && Path(`/api`)"
      - "traefik.http.routers.mern-chatapp-backend-secure.tls=true"
      - "traefik.http.routers.mern-chatapp-backend-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.mern-chatapp-backend-secure.service=mern-chatapp-backend"
      - "traefik.http.services.mern-chatapp-backend.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"

  mern-chatapp-frontend:
    build: ./client
    container_name: mern-chatapp-frontend
    networks:
      - proxy
    ports:
      - "5001:80"
    depends_on:
      - "mern-chatapp-backend"
    environment:
      - REACT_ENV=$REACT_ENV
      - API_ENDPOINT=$API_ENDPOINT
      - SOCKET_ENDPOINT=$SOCKET_ENDPOINT
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mern-chatapp-frontend.entrypoints=http"
      - "traefik.http.routers.mern-chatapp-frontend.rule=Host(`mern-chatapp.brehak.com`)"
      - "traefik.http.middlewares.mern-chatapp-frontend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mern-chatapp-frontend.middlewares=mern-chatapp-frontend-https-redirect"
      - "traefik.http.routers.mern-chatapp-frontend-secure.entrypoints=https"
      - "traefik.http.routers.mern-chatapp-frontend-secure.rule=Host(`mern-chatapp.brehak.com`)"
      - "traefik.http.routers.mern-chatapp-frontend-secure.tls=true"
      - "traefik.http.routers.mern-chatapp-frontend-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.mern-chatapp-frontend-secure.service=mern-chatapp-frontend"
      - "traefik.http.services.mern-chatapp-frontend.loadbalancer.server.port=5001"
      - "traefik.docker.network=proxy"

  redis-chatapp:
    image: "redislabs/redismod"
    container_name: mern-chatapp-redis
    environment:
      - REDIS_AOF_ENABLED=no
      - REDIS_PASSWORD=$REDIS_PASSWORD
    networks:
      - backend
    ports:
      - "5002:6379"
    volumes:
      - ./docker/redis:/data
    entrypoint: >
      redis-server
        --loadmodule /usr/lib/redis/modules/redisearch.so
        --loadmodule /usr/lib/redis/modules/rejson.so
        --appendonly yes

networks:
  proxy:
    external: true
  mongodb:
  backend:
